### ISSUE TITLE
Link to Twitter thread is incorrect

### ISSUE THREAD

**Issue by steven2358** [ademidun/ademidun#1]
The link to the Twitter thread on Solana / FTX is incorrect. It points to YouTube.

**Comment by ademidun** [comment]
Thanks so much for taking the time to point this out Steven! I've fixed it in https://github.com/ademidun/ademidun/commit/ee1ad4895706d734150258f5906d0032a50af938

The correct link is: https://twitter.com/tomiwa1a/status/1482556249883365376
